"""Add sort_order to stock_holdings

Revision ID: 0f3a791753e2
Revises: 2f1edb3484b4
Create Date: 2026-03-20 23:28:23.914714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f3a791753e2'
down_revision: Union[str, Sequence[str], None] = '2f1edb3484b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_holdings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_holdings', schema=None) as batch_op:
        batch_op.drop_column('sort_order')

    # ### end Alembic commands ###
