"""add linked_account_id to stock_accounts

Revision ID: 2f1edb3484b4
Revises: eb4485c43af2
Create Date: 2026-03-16 16:55:29.193966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f1edb3484b4'
down_revision: Union[str, Sequence[str], None] = 'eb4485c43af2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linked_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_stock_accounts_linked_account', 'accounts', ['linked_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_accounts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_stock_accounts_linked_account', type_='foreignkey')
        batch_op.drop_column('linked_account_id')

    # ### end Alembic commands ###
