"""Add exchange to stock_holdings

Revision ID: a7e8099bdbfc
Revises: 0f3a791753e2
Create Date: 2026-03-20 23:34:23.172856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7e8099bdbfc'
down_revision: Union[str, Sequence[str], None] = '0f3a791753e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_holdings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exchange', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_holdings', schema=None) as batch_op:
        batch_op.drop_column('exchange')

    # ### end Alembic commands ###
