"""add brokerage and account_type to stock_accounts

Revision ID: eb4485c43af2
Revises: 982fdf094b0e
Create Date: 2026-03-16 16:39:42.083517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb4485c43af2'
down_revision: Union[str, Sequence[str], None] = '982fdf094b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brokerage', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('account_type', sa.Text(), nullable=False, server_default='cash'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_accounts', schema=None) as batch_op:
        batch_op.drop_column('account_type')
        batch_op.drop_column('brokerage')

    # ### end Alembic commands ###
